version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "65:63:21:f1:cd:b0:f8:44:4a:4f:13:6d:71:9b:28:26"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
